### ISSUE TITLE
Autocomplete not working?

### ISSUE THREAD

**Issue by imh1kiko** [MCJack123/vscode-computercraft#3]
I'm not sure what's going on. I have it set on lua, went through settings for any kind of auto-completion bs, reinstalled and disabled on by one, I can't get this to work. Any ideas?

https://user-images.githubusercontent.com/23316799/202699322-480a7013-85ac-41d5-a4c6-a40ceffbdb94.mp4

**Comment by Shroototem** [comment]
Bump

**Comment by MCJack123** [comment]
You need to save the file first to get autocompletion to function. This isn't something I can readily fix unfortunately.
