### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by KingofMidnight** [MCJack123/vscode-computercraft#5]
i have been trying to code something for a turtle for a while now i really hope u can update this to work, I'm trying to code a startup.lua for a turtle in Minecraft 1.18 but so far i could only find your thing on vscode

**Comment by MCJack123** [comment]
Works fine for me.

**Comment by MCJack123** [comment]
Note that autocomplete doesn't work when used in combination with CraftOS-PC Remote, which isn't possible to work around unfortunately.
