### ISSUE TITLE
Extension with Lua extension enabled completely breaks autocomplete

### ISSUE THREAD

**Issue by Nukiloco** [MCJack123/vscode-computercraft#6]
Not sure what I'm doing wrong currently though having both the lua extension and the computercraft extension enable doesn't allow for any of the autocomplete fields to work.
For example typing "fs" will show up the fs result but then typing a dot will not show all the methods under it.
If I turn off the lua extension, this will completely work fine.
I'm on Linux currently so I'm not sure if that has any effect on this.

**Comment by Chase22** [comment]
I run into the same problem. VSCode also does not recognise computercraft globals

**Comment by scottbot95** [comment]
Also hitting this issue with VSCode on Windows. It would appear an update to the lua extension broke this one at some point.

ComputerCraft Extension: 1.1.1
Lua: 3.7.0

**Comment by MCJack123** [comment]
Unfortunately, this is an issue with the Lua extension - it overrides a significant portion of autocompletion, which breaks this extension. I'm not able to fix this issue.
