### ISSUE TITLE
no autocompletions when using CraftOS along side.

### ISSUE THREAD

**Issue by LazrProductions** [MCJack123/vscode-computercraft#7]
There are no autocompletions when editing remote files on CraftOS.

**Comment by MCJack123** [comment]
This is a limitation of VS Code that is impossible to get around at the moment.

**Comment by wojtakbar** [comment]
> This is a limitation of VS Code that is impossible to get around at the moment.

Could you elaborate on which limitation you are talking about, im not that into electron (or whatever vscode is made on). It might not be that useful, but will give an insight

**Comment by MCJack123** [comment]
VS Code simply does not run completion extensions in a remote file context. There's nothing to really explain, that's just how it is.

**Comment by TheHomecraft** [comment]
Had the same Issue and made it work by removing 'scheme: "file"' from [here](https://github.com/MCJack123/vscode-computercraft/blob/340bf693760fee100e2001ca75391b1c055e65be/src/extension.ts#L8). Now it works even in those CraftOS-PC Remote files.
