### ISSUE TITLE
Publish to open-vsx.org as VSCode users cannot use the Microsoft Marketplace legally

### ISSUE THREAD

**Issue by creeloper27** [MCJack123/vscode-computercraft#8]
It would be super nice if you could also publish this extension on the [Open VSX Registry](https://open-vsx.org/) as people using [VSCodium](https://vscodium.com/) (Free/Libre Open Source Software Binaries of VS Code) [cannot legally use the Microsoft Marketplace](https://github.com/microsoft/vscode/issues/31168) so me and other users that use [VSCodium](https://vscodium.com/) need to manually go on the [Microsoft Marketplace Website](https://marketplace.visualstudio.com/vscode), find the estension there ([here](https://marketplace.visualstudio.com/items?itemName=jackmacwindows.vscode-computercraft)), click `Download Extension` then install the downloaded .vsix file like shown [here](https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix) which is quite an annoying and user unfriendly process.
To publish extensions on the [Open VSX Registry](https://open-vsx.org/) there is [this guide](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

Thanks in advance and Especially Thanks for Making this Awesome Extension! :D

**Comment by MCJack123** [comment]
It was already on there, but hadn't been updated in some time - [I've updated it to the latest version now](https://open-vsx.org/extension/JackMacWindows/craftos-pc).

**Comment by creeloper27** [comment]
> It was already on there, but hadn't been updated in some time - [I've updated it to the latest version now](https://open-vsx.org/extension/JackMacWindows/craftos-pc).

Wait no, this issue is not referring to [vscode-craftos-pc](https://github.com/MCJack123/vscode-craftos-pc), this Issue refers to [vscode-computercraft](https://github.com/MCJack123/vscode-computercraft) (the current repository).
[vscode-computercraft](https://github.com/MCJack123/vscode-computercraft) [is only present on the Microsoft Marketplace](https://marketplace.visualstudio.com/items?itemName=jackmacwindows.vscode-computercraft) as of now (I have checked your [open-vsx profile](https://open-vsx.org/namespace/JackMacWindows) and searched for "computercraft" on[open-vsx](https://open-vsx.org/) and it's not showing up in neither).

If you end up uploading this project to [open-vsx](https://open-vsx.org/) as well you also need to update the description of your CraftOS-PC for VS Code ([vscode-craftos-pc](https://github.com/MCJack123/vscode-craftos-pc)) [here](https://open-vsx.org/extension/JackMacWindows/craftos-pc#:~:text=ComputerCraft%20by%20JackMacWindows%20(me!)%20for%20ComputerCraft%20autocomplete).

**Comment by MCJack123** [comment]
Fixed, https://open-vsx.org/extension/JackMacWindows/vscode-computercraft

**Comment by creeloper27** [comment]
Thank you very much! :D

> Fixed, https://open-vsx.org/extension/JackMacWindows/vscode-computercraft
